
export const translations = {
  en: {
    appTitle: "Kitchen King",
    appSubtitle: "Professional Cooking Assistant",
    startOver: "Start Over",
    safetyNotes: "Safety Notes",
    detectedItems: "Detected Items",
    recipes: "Recipes",
    quickMode: "Quick (15m)",
    noGas: "No Gas",
    saved: "Saved",
    save: "Save",
    clearFilters: "Clear Filters",
    noRecipesMatch: "No recipes match your filters.",
    foodSavingTips: "Food Saving Tips",
    quickPrefs: "Quick Preferences",
    diet: "Diet",
    veg: "Veg",
    nonVeg: "Non-Veg",
    servings: "Servings",
    time: "Time",
    minutes: "minutes",
    snapFridge: "Snap your Fridge",
    analyzeSub: "Analyze items and get recipes",
    getRecipes: "Get Recipes",
    analyzing: "Analyzing Fridge...",
    searchPlaceholder: "Search ingredients (e.g. Potato, Paneer...)",
    or: "OR",
    go: "Go",
    kitchenAI: "Kitchen AI",
    kitchenSub: "Snap a photo or type what you have to get professional recipes instantly.",
    myCookbook: "My Cookbook",
    cookbookSub: "Your collection of favorite recipes.",
    noSaved: "No saved recipes yet.",
    starRecipes: "Star recipes to see them here!",
    back: "Back",
    selectedRecipe: "Selected Recipe",
    watchVideo: "Watch Video Tutorial",
    clickToSearch: "Click to search on YouTube",
    ingredients: "Ingredients",
    steps: "Steps",
    expertTip: "Expert Tip",
    expertTipText: "Ensure all vegetables are washed thoroughly before prep!",
    removeFromCookbook: "Remove from Cookbook",
    saveToCookbook: "Save to My Cookbook",
    share: "Share",
    copied: "Recipe copied to clipboard!",
    swap: "Swap",
    subSuggestion: "Substitute Suggestion",
    welcomeTitle: "Welcome to Kitchen King",
    welcomeText: "Your professional AI cooking assistant. Transform ingredients into delicious meals instantly.",
    snapTitle: "Snap & Analyze",
    snapText: "Simply take a photo of your fridge or pantry. Our AI identifies ingredients and their freshness automatically.",
    cookTitle: "Cook & Save",
    cookText: "Get personalized recipes based on what you have. Save your favorites to your digital cookbook!",
    skip: "Skip",
    next: "Next",
    letsCook: "Let's Cook!",
    timeLabel: "Time",
    difficultyLabel: "Difficulty",
    caloriesLabel: "Calories",
    
    // Meal Plan
    weeklyPlan: "Weekly Meal Plan",
    addToPlan: "Add to Plan",
    days: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    planUpdated: "Meal plan updated",
    
    // Auth
    login: "Login",
    register: "Register",
    username: "Username",
    pin: "PIN (4 digits)",
    logout: "Logout",
    loginError: "Invalid username or PIN",
    registerError: "Username already exists",
    welcomeBack: "Welcome back,",
    createAccount: "Create your secure offline account",
    loginSub: "Access your personal cookbook",
    guestLogin: "Continue as Guest",

    // Download
    download: "Download",
    downloaded: "Saved",
    downloadImage: "Image (JPG)",
    downloadPdf: "Document (PDF)",
    fileSaved: "File saved successfully",
    checkDownloads: "Check your downloads folder",
    
    // New Footer Links
    footerTerms: "Terms",
    footerPrivacy: "Privacy",
    footerAbout: "About",
    
    // Info Page Titles
    termsTitle: "Terms & Conditions",
    privacyTitle: "Privacy Policy",
    aboutTitle: "About Us",
    
    // Info Content
    termsContent: `By using Kitchen King, you agree to these terms. 
    1. Usage: This app is for personal, non-commercial use.
    2. AI Disclaimer: Recipes and nutritional info are generated by AI (Gemini). While usually accurate, please verify important details, especially regarding allergies or food safety.
    3. Safety: Always check ingredients for freshness before cooking. The app's freshness detection is an estimation only.`,
    
    privacyContent: `Your privacy is important to us.
    1. Camera Usage: We use the camera solely to analyze your fridge contents.
    2. Data Processing: Images are processed securely via the Google Gemini API. We do not permanently store your photos on our servers.
    3. Local Storage: Your preferences and saved recipes are stored locally on your device.`,
    
    aboutContent: `Kitchen King is your smart kitchen companion designed to reduce food waste and spark culinary creativity.
    
    Powered by Google's Gemini AI, we help you turn whatever is in your fridge into delicious meals. Whether you are a beginner or a pro, we make cooking easy, fun, and efficient.`
  },
  hi: {
    appTitle: "किचन किंग",
    appSubtitle: "आपका कुकिंग असिस्टेंट",
    startOver: "शुरू से करें",
    safetyNotes: "सुरक्षा सूचना",
    detectedItems: "मिली हुई वस्तुएं",
    recipes: "व्यंजन (रेसिपी)",
    quickMode: "झटपट (15 मिनट)",
    noGas: "बिना गैस",
    saved: "सहेजा गया",
    save: "सहेजें",
    clearFilters: "फिल्टर हटाएं",
    noRecipesMatch: "कोई रेसिपी नहीं मिली।",
    foodSavingTips: "बचत के नुस्खे",
    quickPrefs: "प्राथमिकताएं",
    diet: "आहार",
    veg: "शाकाहारी",
    nonVeg: "मांसाहारी",
    servings: "लोग",
    time: "समय",
    minutes: "मिनट",
    snapFridge: "फ्रिज की फोटो लें",
    analyzeSub: "सामान पहचानें और रेसिपी पाएं",
    getRecipes: "रेसिपी खोजें",
    analyzing: "जांच चल रही है...",
    searchPlaceholder: "सामग्री खोजें (जैसे आलू, पनीर...)",
    or: "या",
    go: "खोजें",
    kitchenAI: "किचन AI",
    kitchenSub: "फोटो लें या सामग्री टाइप करें और तुरंत प्रोफेशनल रेसिपी पाएं।",
    myCookbook: "मेरी रसोई किताब",
    cookbookSub: "आपकी पसंदीदा रेसिपी का संग्रह।",
    noSaved: "अभी कोई रेसिपी सहेजी नहीं गई है।",
    starRecipes: "रेसिपी को स्टार (⭐) करें!",
    back: "वापस",
    selectedRecipe: "चुनी गई रेसिपी",
    watchVideo: "वीडियो देखें",
    clickToSearch: "YouTube पर खोजने के लिए क्लिक करें",
    ingredients: "सामग्री",
    steps: "बनाने की विधि",
    expertTip: "ज़रूरी सुझाव",
    expertTipText: "पकाने से पहले सभी सब्जियों को अच्छी तरह धो लें!",
    removeFromCookbook: "किताब से हटाएं",
    saveToCookbook: "किताब में सहेजें",
    share: "शेयर",
    copied: "रेसिपी कॉपी कर ली गई!",
    swap: "बदलें",
    subSuggestion: "वैकल्पिक सुझाव",
    welcomeTitle: "किचन किंग में स्वागत है",
    welcomeText: "आपका प्रोफेशनल AI कुकिंग असिस्टेंट। सामग्री को तुरंत स्वादिष्ट भोजन में बदलें।",
    snapTitle: "फोटो लें और परखें",
    snapText: "बस अपने फ्रिज या पेंट्री की फोटो लें। हमारा AI अपने आप सामग्री और ताजगी पहचान लेगा।",
    cookTitle: "पकाएं और सहेजें",
    cookText: "आपके पास जो है, उसके आधार पर रेसिपी पाएं। अपनी पसंदीदा रेसिपी को डिजिटल कुकबुक में सेव करें!",
    skip: "छोड़ें",
    next: "अगला",
    letsCook: "चलिए पकाते हैं!",
    timeLabel: "समय",
    difficultyLabel: "कठिनाई",
    caloriesLabel: "कैलोरी",

    // Meal Plan
    weeklyPlan: "साप्ताहिक भोजन योजना",
    addToPlan: "योजना में जोड़ें",
    days: ["सोम", "मंगल", "बुध", "गुरु", "शुक्र", "शनि", "रवि"],
    planUpdated: "योजना अपडेट की गई",

    // Auth
    login: "लॉग इन",
    register: "रजिस्टर",
    username: "यूज़रनेम",
    pin: "पिन (4 अंक)",
    logout: "लॉग आउट",
    loginError: "गलत यूज़रनेम या पिन",
    registerError: "यूज़रनेम पहले से मौजूद है",
    welcomeBack: "स्वागत है,",
    createAccount: "सुरक्षित ऑफ़लाइन खाता बनाएं",
    loginSub: "अपनी व्यक्तिगत कुकबुक एक्सेस करें",
    guestLogin: "गेस्ट के रूप में जारी रखें",

    // Download
    download: "डाउनलोड",
    downloaded: "सेव हो गया",
    downloadImage: "इमेज (JPG)",
    downloadPdf: "दस्तावेज़ (PDF)",
    fileSaved: "फाइल सफलतापूर्वक सेव हो गई",
    checkDownloads: "अपना डाउनलोड फोल्डर चेक करें",

    // New Footer Links
    footerTerms: "नियम",
    footerPrivacy: "गोपनीयता",
    footerAbout: "परिचय",

    // Info Page Titles
    termsTitle: "नियम और शर्तें",
    privacyTitle: "गोपनीयता नीति",
    aboutTitle: "हमारे बारे में",

    // Info Content
    termsContent: `किचन किंग का उपयोग करके, आप इन शर्तों से सहमत हैं।
    1. उपयोग: यह ऐप केवल व्यक्तिगत, गैर-व्यावसायिक उपयोग के लिए है।
    2. AI अस्वीकरण: रेसिपी और पोषण संबंधी जानकारी AI (जेमिनी) द्वारा उत्पन्न होती है। कृपया महत्वपूर्ण विवरणों की पुष्टि करें, विशेष रूप से एलर्जी या खाद्य सुरक्षा के संबंध में।
    3. सुरक्षा: पकाने से पहले हमेशा सामग्री की ताजगी की जांच करें। ऐप का ताजगी का पता लगाना केवल एक अनुमान है।`,

    privacyContent: `आपकी गोपनीयता हमारे लिए महत्वपूर्ण है।
    1. कैमरा का उपयोग: हम केवल आपके फ्रिज की सामग्री का विश्लेषण करने के लिए कैमरे का उपयोग करते हैं।
    2. डेटा प्रोसेसिंग: छवियों को Google जेमिनी API के माध्यम से सुरक्षित रूप से प्रोसेस किया जाता है। हम आपकी तस्वीरों को अपने सर्वर पर स्थायी रूप से संग्रहीत नहीं करते हैं।
    3. स्थानीय भंडारण: आपकी प्राथमिकताएं और सहेजी गई रेसिपी आपके डिवाइस पर स्थानीय रूप से संग्रहीत हैं।`,

    aboutContent: `किचन किंग आपका स्मार्ट किचन साथी है जिसे भोजन की बर्बादी को कम करने और खाना पकाने में रचनात्मकता लाने के लिए डिज़ाइन किया गया है।

    Google के जेमिनी AI द्वारा संचालित, हम आपकी मदद करते हैं कि आपके फ्रिज में जो कुछ भी है उसे स्वादिष्ट भोजन में बदल दें। चाहे आप शुरुआती हों या प्रो, हम खाना बनाना आसान, मजेदार और कुशल बनाते हैं।`
  }
};
