import React, { useState, useEffect, useRef } from 'react';
import { Recipe } from '../types';
import { getIngredientSubstitution } from '../geminiService';
import { useLanguage } from '../LanguageContext';
import { useAuth } from '../AuthContext';
import { jsPDF } from "jspdf";

interface RecipeModalProps {
  recipe: Recipe;
  onClose: () => void;
  isSaved: boolean;
  onToggleSave: () => void;
  availableIngredients?: string[];
}

export const RecipeModal: React.FC<RecipeModalProps> = ({ recipe, onClose, isSaved, onToggleSave, availableIngredients = [] }) => {
  const { t, language } = useLanguage();
  const { user } = useAuth();
  
  const [substitutions, setSubstitutions] = useState<Record<string, string>>({});
  const [loadingSub, setLoadingSub] = useState<Record<string, boolean>>({});
  const [isCopied, setIsCopied] = useState(false);
  const [isDownloaded, setIsDownloaded] = useState(false);
  const [plannedDays, setPlannedDays] = useState<string[]>([]);
  const [showDownloadMenu, setShowDownloadMenu] = useState(false);
  const downloadMenuRef = useRef<HTMLDivElement>(null);

  // Close menu when clicking outside
  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (downloadMenuRef.current && !downloadMenuRef.current.contains(event.target as Node)) {
        setShowDownloadMenu(false);
      }
    };
    document.addEventListener("mousedown", handleClickOutside);
    return () => {
      document.removeEventListener("mousedown", handleClickOutside);
    };
  }, []);

  // Load planned days on mount
  useEffect(() => {
    if (!user) return;
    try {
      const planKey = `mealplan_${user.username}`;
      const savedPlan = JSON.parse(localStorage.getItem(planKey) || '{}');
      const days: string[] = [];
      
      // Check which days have this recipe
      Object.keys(savedPlan).forEach(day => {
        const dayRecipes: Recipe[] = savedPlan[day] || [];
        if (dayRecipes.some(r => r.id === recipe.id || (r.nameEn === recipe.nameEn))) {
          days.push(day);
        }
      });
      setPlannedDays(days);
    } catch (e) {
      console.error("Error loading meal plan", e);
    }
  }, [user, recipe]);

  const togglePlanDay = (dayIndex: number) => {
    if (!user) return;
    
    const dayKey = dayIndex.toString(); // 0-6
    const planKey = `mealplan_${user.username}`;
    let savedPlan: Record<string, Recipe[]> = {};
    
    try {
      savedPlan = JSON.parse(localStorage.getItem(planKey) || '{}');
    } catch (e) {
      savedPlan = {};
    }

    let dayRecipes = savedPlan[dayKey] || [];
    const exists = dayRecipes.some(r => r.id === recipe.id || (r.nameEn === recipe.nameEn));

    if (exists) {
      // Remove
      dayRecipes = dayRecipes.filter(r => !(r.id === recipe.id || (r.nameEn === recipe.nameEn)));
      setPlannedDays(prev => prev.filter(d => d !== dayKey));
    } else {
      // Add
      dayRecipes.push(recipe);
      setPlannedDays(prev => [...prev, dayKey]);
    }

    savedPlan[dayKey] = dayRecipes;
    localStorage.setItem(planKey, JSON.stringify(savedPlan));
  };

  const handleShare = async () => {
    const shareData = {
      title: `Kitchen King: ${recipe.nameEn}`,
      text: `Check out this recipe: ${recipe.nameEn} (${recipe.nameHi})\n\nIngredients:\n${recipe.ingredientsEn.join('\n')}\n\nGenerated by Kitchen King`,
      url: window.location.href,
    };

    try {
      if (navigator.share && navigator.canShare(shareData)) {
        await navigator.share(shareData);
      } else {
        const textToCopy = `${shareData.title}\n\n${shareData.text}`;
        await navigator.clipboard.writeText(textToCopy);
        setIsCopied(true);
        setTimeout(() => setIsCopied(false), 2000);
      }
    } catch (err) {
      console.error('Error sharing:', err);
    }
  };

  const generateCanvas = (): HTMLCanvasElement | null => {
    const mainName = language === 'hi' ? recipe.nameHi : recipe.nameEn;
    const subName = language === 'hi' ? recipe.nameEn : recipe.nameHi;
    const ingredients = language === 'hi' ? recipe.ingredientsHi : recipe.ingredientsEn;
    const steps = language === 'hi' ? recipe.stepsHi : recipe.stepsEn;

    // Use A4 proportions approx 1:1.41
    // Width 800px -> Height target ~1128px
    const width = 800;
    
    // Calculate required height based on content
    // We create a temporary ctx to measure text
    const tempCanvas = document.createElement('canvas');
    const tempCtx = tempCanvas.getContext('2d');
    if (!tempCtx) return null;
    tempCtx.font = '22px sans-serif'; // Body font

    const padding = 60;
    
    // Estimation helper
    const estimateHeight = (text: string, maxWidth: number) => {
        const words = text.split(' ');
        let line = '';
        let lines = 1;
        for (let n = 0; n < words.length; n++) {
            const testLine = line + words[n] + ' ';
            const metrics = tempCtx.measureText(testLine);
            if (metrics.width > maxWidth && n > 0) {
                line = words[n] + ' ';
                lines++;
            } else {
                line = testLine;
            }
        }
        return lines * 30; // Line height
    };

    let contentHeight = 0;
    
    // Header space
    contentHeight += 350; 

    // Ingredients
    contentHeight += 60; // Title
    ingredients.forEach(ing => {
        contentHeight += estimateHeight(ing, width - (padding * 2) - 35) + 10;
    });
    contentHeight += 40; // Spacer

    // Steps
    contentHeight += 60; // Title
    steps.forEach(step => {
        contentHeight += estimateHeight(step, width - (padding * 2) - 45) + 15;
    });

    contentHeight += 100; // Footer

    // Ensure at least A4 ratio height, but allow growing
    const minHeight = width * 1.414;
    const totalHeight = Math.max(minHeight, contentHeight);

    const canvas = document.createElement('canvas');
    canvas.width = width;
    canvas.height = totalHeight;
    const ctx = canvas.getContext('2d');

    if (!ctx) return null;

    // Background
    ctx.fillStyle = '#ffffff';
    ctx.fillRect(0, 0, width, totalHeight);

    let currentY = 80;

    // Helper: Wrap Text
    const wrapText = (text: string, x: number, y: number, maxWidth: number, lineHeight: number) => {
        const words = text.split(' ');
        let line = '';

        for (let n = 0; n < words.length; n++) {
            const testLine = line + words[n] + ' ';
            const metrics = ctx.measureText(testLine);
            const testWidth = metrics.width;
            if (testWidth > maxWidth && n > 0) {
                ctx.fillText(line, x, y);
                line = words[n] + ' ';
                y += lineHeight;
            } else {
                line = testLine;
            }
        }
        ctx.fillText(line, x, y);
        return y + lineHeight;
    };

    // --- Header ---
    ctx.textAlign = 'center';
    
    // Brand
    ctx.fillStyle = '#059669'; // Emerald-600
    ctx.font = 'bold 24px sans-serif';
    ctx.fillText('KITCHEN KING', width / 2, currentY);
    currentY += 50;

    // Title
    ctx.fillStyle = '#111827'; // Gray-900
    ctx.font = 'bold 40px sans-serif';
    currentY = wrapText(mainName, width / 2, currentY, width - (padding * 2), 50);
    currentY += 10;

    // Sub Title
    ctx.fillStyle = '#059669'; // Emerald-600
    ctx.font = 'italic 24px sans-serif';
    ctx.fillText(subName, width / 2, currentY);
    currentY += 50;

    // Stats Bar
    ctx.fillStyle = '#f0fdf4'; // emerald-50
    ctx.fillRect(padding, currentY, width - (padding * 2), 60);
    ctx.fillStyle = '#065f46'; // emerald-800
    ctx.font = 'bold 20px sans-serif';
    // Clean text for stats
    const tTime = language === 'hi' ? 'समय' : 'Time';
    const tDiff = language === 'hi' ? 'कठिनाई' : 'Diff';
    const tCal = language === 'hi' ? 'कैलोरी' : 'Cals';
    
    const statText = `${tTime}: ${recipe.time}   |   ${tDiff}: ${recipe.difficulty}   |   ${tCal}: ${recipe.calories}`;
    ctx.fillText(statText, width / 2, currentY + 38);
    currentY += 100;

    // --- Content ---
    ctx.textAlign = 'left';
    ctx.fillStyle = '#111827';

    // Ingredients Section
    ctx.font = 'bold 28px sans-serif';
    ctx.fillText((language === 'hi' ? 'सामग्री' : 'INGREDIENTS'), padding, currentY);
    ctx.beginPath();
    ctx.moveTo(padding, currentY + 10);
    ctx.lineTo(width - padding, currentY + 10);
    ctx.strokeStyle = '#e5e7eb';
    ctx.stroke();
    currentY += 50;

    ctx.font = '22px sans-serif';
    ingredients.forEach(ing => {
        // Bullet point wrap
        const bullet = "• ";
        ctx.fillText(bullet, padding + 10, currentY);
        currentY = wrapText(ing, padding + 35, currentY, width - (padding * 2) - 35, 30);
        currentY += 10;
    });

    currentY += 40;

    // Steps Section
    ctx.font = 'bold 28px sans-serif';
    ctx.fillText((language === 'hi' ? 'विधि' : 'STEPS'), padding, currentY);
    ctx.beginPath();
    ctx.moveTo(padding, currentY + 10);
    ctx.lineTo(width - padding, currentY + 10);
    ctx.strokeStyle = '#e5e7eb';
    ctx.stroke();
    currentY += 50;

    ctx.font = '22px sans-serif';
    steps.forEach((step, i) => {
        const stepPrefix = `${i + 1}.`;
        ctx.fillText(stepPrefix, padding + 10, currentY);
        currentY = wrapText(step, padding + 45, currentY, width - (padding * 2) - 45, 35);
        currentY += 15; // Extra spacing between steps
    });

    // --- Footer ---
    ctx.textAlign = 'center';
    ctx.fillStyle = '#9ca3af'; // gray-400
    ctx.font = '16px sans-serif';
    // Stick footer to bottom or after content
    const footerY = Math.max(currentY + 60, totalHeight - 40);
    ctx.fillText('Generated by Kitchen King • www.kitchenking-ai.app', width / 2, footerY);
    
    return canvas;
  };

  const handleDownloadImage = () => {
    const canvas = generateCanvas();
    if (!canvas) return;

    try {
        const dataUrl = canvas.toDataURL('image/jpeg', 0.9);
        const link = document.createElement('a');
        link.download = `kitchenking_${recipe.nameEn.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.jpg`;
        link.href = dataUrl;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        
        setIsDownloaded(true);
        setTimeout(() => setIsDownloaded(false), 3000);
    } catch (e) {
        console.error("Download failed", e);
    }
    setShowDownloadMenu(false);
  };

  const handleDownloadPDF = () => {
    const canvas = generateCanvas();
    if (!canvas) return;

    try {
        const imgData = canvas.toDataURL('image/jpeg', 0.9);
        const pdf = new jsPDF({
            orientation: 'portrait',
            unit: 'mm',
            format: 'a4'
        });
        
        const imgProps = pdf.getImageProperties(imgData);
        const pdfWidth = pdf.internal.pageSize.getWidth();
        const pdfHeight = pdf.internal.pageSize.getHeight();
        
        // Scale to fit width, but if it exceeds height, we just center it vertically or fit it
        // Ideally we fit to width
        let finalWidth = pdfWidth;
        let finalHeight = (imgProps.height * pdfWidth) / imgProps.width;

        // If height is too big for one page, we scale it down to fit the page
        // This ensures "A4 paper size" is respected as a single page handout
        if (finalHeight > pdfHeight) {
            const ratio = pdfHeight / finalHeight;
            finalWidth = finalWidth * ratio;
            finalHeight = pdfHeight;
        }

        const x = (pdfWidth - finalWidth) / 2;
        const y = (pdfHeight - finalHeight) / 2; // Center vertically

        pdf.addImage(imgData, 'JPEG', x, y, finalWidth, finalHeight);
        pdf.save(`kitchenking_${recipe.nameEn.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.pdf`);
        
        setIsDownloaded(true);
        setTimeout(() => setIsDownloaded(false), 3000);
    } catch (e) {
        console.error("PDF Download failed", e);
    }
    setShowDownloadMenu(false);
  };

  const handleSubstitute = async (ingredient: string) => {
    if (substitutions[ingredient]) return; // Already fetched

    setLoadingSub(prev => ({ ...prev, [ingredient]: true }));
    try {
      const sub = await getIngredientSubstitution(ingredient, recipe.nameEn, availableIngredients);
      setSubstitutions(prev => ({ ...prev, [ingredient]: sub }));
    } catch (e) {
      console.error(e);
      setSubstitutions(prev => ({ ...prev, [ingredient]: "Could not find substitute." }));
    } finally {
      setLoadingSub(prev => ({ ...prev, [ingredient]: false }));
    }
  };

  const videoSearchUrl = `https://www.youtube.com/results?search_query=${encodeURIComponent(`${recipe.nameEn} recipe cooking tutorial`)}`;

  // Determine what to show based on language
  const mainName = language === 'hi' ? recipe.nameHi : recipe.nameEn;
  const subName = language === 'hi' ? recipe.nameEn : recipe.nameHi;
  const mainIngredients = language === 'hi' ? recipe.ingredientsHi : recipe.ingredientsEn;
  const subIngredients = language === 'hi' ? recipe.ingredientsEn : recipe.ingredientsHi;
  const mainSteps = language === 'hi' ? recipe.stepsHi : recipe.stepsEn;
  const subSteps = language === 'hi' ? recipe.stepsEn : recipe.stepsHi;

  return (
    <div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-sm flex items-end sm:items-center justify-center p-0 sm:p-4 animate-in fade-in duration-200">
      <div className="bg-white w-full max-w-lg h-[90vh] sm:h-auto sm:max-h-[80vh] overflow-y-auto rounded-t-[40px] sm:rounded-[40px] shadow-2xl relative animate-in slide-in-from-bottom duration-300">
        
        {/* Success Toast */}
        {isDownloaded && (
          <div className="fixed bottom-10 left-1/2 -translate-x-1/2 z-[100] w-full max-w-sm px-4">
             <div className="bg-gray-900/90 backdrop-blur-md text-white px-6 py-4 rounded-2xl shadow-2xl flex items-center gap-4 border border-white/10 animate-in slide-in-from-bottom-4 fade-in duration-300">
               <div className="bg-emerald-500 rounded-full p-1 shrink-0">
                 <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 text-white" viewBox="0 0 20 20" fill="currentColor">
                   <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                 </svg>
               </div>
               <div className="flex-1">
                 <p className="font-bold text-sm">{t.fileSaved}</p>
                 <p className="text-[11px] text-gray-400">{t.checkDownloads}</p>
               </div>
             </div>
          </div>
        )}
      
        <div className="sticky top-0 right-0 p-4 flex justify-between items-center bg-white/80 backdrop-blur-md z-20 border-b">
          <div className="flex gap-2 overflow-x-auto scrollbar-hide items-center">
            <button 
              onClick={onToggleSave}
              className={`flex items-center gap-2 px-3 py-2 rounded-full text-xs font-bold transition-colors whitespace-nowrap ${
                isSaved 
                ? 'bg-emerald-600 text-white shadow-lg' 
                : 'bg-emerald-50 text-emerald-700 hover:bg-emerald-100'
              }`}
            >
              <span>{isSaved ? '⭐' : '☆'}</span> 
              {isSaved ? t.saved : t.save}
            </button>
            <button 
              onClick={handleShare}
              className={`flex items-center gap-2 px-3 py-2 rounded-full text-xs font-bold transition-colors whitespace-nowrap ${
                isCopied
                ? 'bg-emerald-600 text-white'
                : 'bg-emerald-50 text-emerald-700 hover:bg-emerald-100'
              }`}
            >
              <span>{isCopied ? '✅' : '📤'}</span> 
              {isCopied ? (language === 'hi' ? 'कॉपी किया' : 'Copied') : t.share}
            </button>
            
            {/* Download Dropdown */}
            <div className="relative" ref={downloadMenuRef}>
                <button 
                  onClick={() => setShowDownloadMenu(!showDownloadMenu)}
                  className={`flex items-center gap-2 px-3 py-2 rounded-full text-xs font-bold transition-colors whitespace-nowrap ${
                    isDownloaded
                    ? 'bg-emerald-600 text-white'
                    : 'bg-emerald-50 text-emerald-700 hover:bg-emerald-100'
                  }`}
                >
                  <span>{isDownloaded ? '💾' : '⬇️'}</span> 
                  {isDownloaded ? t.downloaded : t.download}
                </button>
                
                {showDownloadMenu && (
                    <div className="absolute top-full left-0 mt-2 w-48 bg-white rounded-xl shadow-xl border border-gray-100 z-50 overflow-hidden animate-in zoom-in-95 duration-100 origin-top-left">
                        <button 
                            onClick={handleDownloadImage}
                            className="w-full text-left px-4 py-3 text-sm text-gray-700 hover:bg-gray-50 flex items-center gap-2"
                        >
                            <span>🖼️</span> {t.downloadImage}
                        </button>
                        <button 
                            onClick={handleDownloadPDF}
                            className="w-full text-left px-4 py-3 text-sm text-gray-700 hover:bg-gray-50 flex items-center gap-2 border-t border-gray-50"
                        >
                            <span>📄</span> {t.downloadPdf}
                        </button>
                    </div>
                )}
            </div>
          </div>
          <button 
            onClick={onClose}
            className="bg-gray-100 p-2 rounded-full hover:bg-gray-200 shrink-0 ml-2"
          >
            ✕
          </button>
        </div>
        <div className="p-8 pt-4">
          <header className="mb-6">
            <span className="text-emerald-600 font-black text-[10px] uppercase tracking-[0.2em]">{t.selectedRecipe}</span>
            <h2 className="text-3xl font-bold text-gray-900 leading-tight">{mainName}</h2>
            <h3 className="text-xl font-medium text-emerald-600 mt-1">{subName}</h3>
            <p className="text-sm text-gray-500 mt-4 italic">"{recipe.whyFit}"</p>
            
            <div className="grid grid-cols-3 gap-2 mt-6">
               <div className="bg-emerald-50 p-3 rounded-2xl text-center">
                  <p className="text-[10px] font-bold text-emerald-600 uppercase">{t.timeLabel}</p>
                  <p className="font-bold text-emerald-900">{recipe.time}</p>
               </div>
               <div className="bg-emerald-50 p-3 rounded-2xl text-center">
                  <p className="text-[10px] font-bold text-emerald-600 uppercase">{t.difficultyLabel}</p>
                  <p className="font-bold text-emerald-900">{recipe.difficulty}</p>
               </div>
               <div className="bg-emerald-50 p-3 rounded-2xl text-center">
                  <p className="text-[10px] font-bold text-emerald-600 uppercase">{t.caloriesLabel}</p>
                  <p className="font-bold text-emerald-900">{recipe.calories}</p>
               </div>
            </div>
          </header>

          {/* YouTube Video Tutorial Section */}
          <a 
            href={videoSearchUrl}
            target="_blank"
            rel="noopener noreferrer"
            title={t.clickToSearch}
            className="block mb-8 group relative rounded-2xl overflow-hidden aspect-video bg-gray-900 shadow-lg border border-gray-800 transition-transform active:scale-[0.98]"
          >
             <div className="absolute inset-0 opacity-40 bg-[radial-gradient(ellipse_at_center,_var(--tw-gradient-stops))] from-gray-700 via-gray-900 to-black"></div>
             
             <div className="absolute inset-0 flex flex-col items-center justify-center z-10">
                <div className="w-16 h-16 bg-red-600 rounded-full flex items-center justify-center shadow-2xl group-hover:scale-110 transition-transform duration-300 ring-4 ring-red-600/30">
                  <svg className="w-7 h-7 text-white fill-current ml-1" viewBox="0 0 24 24"><path d="M8 5v14l11-7z"/></svg>
                </div>
                <p className="mt-4 text-white font-bold text-sm tracking-wider uppercase drop-shadow-md flex items-center gap-2">
                  <span>📺</span> {t.watchVideo}
                </p>
                <p className="text-xs text-gray-400 mt-1">{t.clickToSearch}</p>
             </div>
          </a>

          <section className="mb-8">
            <h4 className="text-lg font-bold text-gray-900 mb-4 border-l-4 border-emerald-500 pl-3">
              {t.ingredients}
            </h4>
            <div className="grid grid-cols-1 gap-4">
              <div className="bg-gray-50 p-4 rounded-2xl">
                <ul className="space-y-3">
                  {mainIngredients.map((ing, i) => (
                    <li key={i} className="text-sm text-gray-700 flex flex-col">
                      <div className="flex items-start justify-between gap-2">
                         <span className="leading-snug">• {ing}</span>
                         <button 
                           onClick={() => handleSubstitute(ing)}
                           disabled={loadingSub[ing]}
                           className="shrink-0 text-[10px] font-bold text-emerald-600 bg-emerald-50 px-2 py-1 rounded-full hover:bg-emerald-100 transition-colors flex items-center gap-1 border border-emerald-100"
                           title="Find substitute"
                         >
                           {loadingSub[ing] ? '...' : `${t.swap} ↻`}
                         </button>
                      </div>
                      {substitutions[ing] && (
                         <div className="mt-2 ml-3 bg-amber-50 p-3 rounded-xl text-xs text-amber-900 border border-amber-100 animate-in slide-in-from-top-1 shadow-sm">
                            <span className="font-bold block mb-0.5 text-amber-700">💡 {t.subSuggestion}:</span> {substitutions[ing]}
                         </div>
                      )}
                    </li>
                  ))}
                </ul>
              </div>
              {/* Secondary Language Ingredients (smaller) */}
              <div className="bg-emerald-50/50 p-4 rounded-2xl opacity-75 hover:opacity-100 transition-opacity">
                <ul className="space-y-1">
                  {subIngredients.map((ing, i) => <li key={i} className="text-sm text-emerald-800">• {ing}</li>)}
                </ul>
              </div>
            </div>
          </section>

          <section className="mb-8">
            <h4 className="text-lg font-bold text-gray-900 mb-4 border-l-4 border-emerald-500 pl-3">
              {t.steps}
            </h4>
            <div className="space-y-6">
              {mainSteps.map((step, i) => (
                <div key={i} className="flex gap-4">
                  <span className="shrink-0 w-8 h-8 rounded-full bg-emerald-600 text-white flex items-center justify-center font-bold text-sm shadow-lg shadow-emerald-200">
                    {i + 1}
                  </span>
                  <div className="space-y-1">
                    <p className="text-sm font-semibold text-gray-800">{step}</p>
                    <p className="text-xs text-emerald-700 font-medium">{subSteps[i]}</p>
                  </div>
                </div>
              ))}
            </div>
          </section>
          
          {/* Meal Plan Section */}
          <section className="mb-6 bg-blue-50/50 p-4 rounded-2xl border border-blue-100">
             <h4 className="text-sm font-bold text-blue-900 mb-3 flex items-center gap-2">
               📅 {t.weeklyPlan}
             </h4>
             <div className="flex justify-between items-center">
                {t.days.map((day, idx) => {
                  const isPlanned = plannedDays.includes(idx.toString());
                  return (
                    <button
                      key={day}
                      onClick={() => togglePlanDay(idx)}
                      className={`w-9 h-9 rounded-full text-xs font-bold transition-all flex items-center justify-center ${
                        isPlanned 
                          ? 'bg-blue-600 text-white shadow-md scale-110' 
                          : 'bg-white text-gray-400 border border-gray-200 hover:border-blue-300'
                      }`}
                      title={`${isPlanned ? 'Remove from' : 'Add to'} ${day}`}
                    >
                      {day.charAt(0)}
                    </button>
                  );
                })}
             </div>
             {plannedDays.length > 0 && (
               <p className="text-[10px] text-blue-600 mt-2 font-medium text-center">
                 {t.planUpdated}
               </p>
             )}
          </section>

          <div className="bg-amber-50 rounded-2xl p-4 border border-amber-100 flex items-start gap-3">
             <span className="text-xl">💡</span>
             <div>
                <p className="text-xs font-bold text-amber-800 uppercase tracking-widest mb-1">{t.expertTip}</p>
                <p className="text-sm text-amber-900">{t.expertTipText}</p>
             </div>
          </div>

          <div className="mt-8">
            <button
              onClick={onToggleSave}
              className={`w-full py-4 rounded-2xl font-bold text-lg shadow-md transition-all flex items-center justify-center gap-2 ${
                isSaved
                ? 'bg-red-50 text-red-600 hover:bg-red-100 border border-red-200'
                : 'bg-emerald-600 text-white hover:bg-emerald-700 shadow-emerald-200'
              }`}
            >
              {isSaved ? (
                <>
                  <span>🗑️</span> {t.removeFromCookbook}
                </>
              ) : (
                <>
                  <span>⭐</span> {t.saveToCookbook}
                </>
              )}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};